### ISSUE TITLE
StatefulWidget issue with Ratatui 0.27

### ISSUE THREAD

**Issue by matta** [joshka/tui-prompts#50]
I could use some help here!

I have a working program with ratatui 0.26.3 but updating it to 0.27 breaks my use of tui-prompts. The build failures have to do with TextPrompt satisfying StatefulWidget. I notice that tui-prompts is still using ratatui 0.26.3 (by looking at Cargo.lock) despite what I say in Cargo.toml.

I'm showing my rust noob colors here.

I don't even know if this is expected to work at the language level, or whether tui-prompts must upgrade before I can, or how to proceed with a fix, etc.

(I know I can avoid using the trait at all by not calling `render_stateful_widget` at all, but I'd like to understand the root issue here before taking that route).

Build error is easiest to see at the https://github.com/matta/sift/pull/36 PR, or:

```text
error[E0277]: the trait bound `TextPrompt<'_>: StatefulWidget` is not satisfied
Error:    --> src/screen/edit.rs:72:38
    |
72  |         frame.render_stateful_widget(prompt, frame.size(), &mut self.text.borrow_mut());
    |               ---------------------- ^^^^^^ the trait `StatefulWidget` is not implemented for `TextPrompt<'_>`
    |               |
    |               required by a bound introduced by this call
    |
    = help: the following other types implement trait `StatefulWidget`:
              &ratatui::widgets::List<'_>
              &ratatui::widgets::Table<'_>
              Scrollbar<'a>
              ratatui::widgets::List<'_>
              ratatui::widgets::Table<'_>
note: required by a bound in `Frame::<'_>::render_stateful_widget`
   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.27.0/src/terminal/frame.rs:126:12
    |
124 |     pub fn render_stateful_widget<W>(&mut self, widget: W, area: Rect, state: &mut W::State)
    |            ---------------------- required by a bound in this associated function
125 |     where
126 |         W: StatefulWidget,
    |            ^^^^^^^^^^^^^^ required by this bound in `Frame::<'_>::render_stateful_widget`
```

**Comment by joshka** [comment]
In rust, 0.x and 0.x+1 are incompatible with each other, so your app is getting two versions of ratatui, one from this lib and one from your app's import. Use [cargo-tree](https://doc.rust-lang.org/cargo/commands/cargo-tree.html) to diagnose these sorts of issues (often with a `-i some-crate` param).

I usually just let dependabot update dependencies automatically once a week (avoids noise), but perhaps should make that more frequent for ratatui updates. I'll cut a manual update to get you going.

**Comment by joshka** [comment]
Should be fixed in https://github.com/joshka/tui-prompts/releases/tag/v0.3.13

**Comment by joshka** [comment]
Also, if you need it in the future, a quick way to unblock yourself for something like this is to pull the source of the library, make the necessary change (i.e. update to ratatui 0.27) and then point your app at the folder in your Cargo.toml (e.g. `ratatui = { version "0.27.0", path = "../ratatui" }`). You can't publish a crate using that approach however, so this is just for local testing.

**Comment by matta** [comment]
> In rust, 0.x and 0.x+1 are incompatible with each other

Ah, this was the bit I was missing. From the cargo book:

I wonder if rustc could be improved to explain, in the error message, that the type does implement a trait named `StatefulWidget`, but from a different package (version). Anyway...

> This is because Cargo uses the convention that only changes in the left-most non-zero component are considered incompatible.

I suppose the lesson is that crate that depends on crates providing ratatui extras is going to need to have some patience, at least until ratatui hits 1.x.

But, hey, since ratatui isn't 1.x yet, why not rename `WidgetRef` to `Widget` and `Widget` to `WidgetWhoopsie`?  🙃  (not serious)

**Comment by joshka** [comment]
> I wonder if rustc could be improved to explain, in the error message, that the type does implement a trait named `StatefulWidget`, but from a different package (version). Anyway...

There's probably a bug for it - somewhere in the [348 issues for "trait bound" "not satisfied"](https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+%22trait+bound%22+%22not+satisfied%22+)...
