### ISSUE TITLE
Regression: Deleting in Strings with multi-byte-characters panics

### ISSUE THREAD

**Issue by frederictobiasc** [joshka/tui-prompts#56]
The panicking I previously fixed in https://github.com/joshka/tui-prompts/pull/41 was reintroduced by https://github.com/joshka/tui-prompts/pull/46

So now, the following panics:
```rust
fn main() {
    let mut test = TextState::new();
    test.push('Ö');
    test.push('a');
    test.backspace();
}
```

Result:

```
thread 'main' panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/string.rs:1449:28:
byte index 1 is not a char boundary; it is inside 'Ö' (bytes 0..2) of `Öa`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by joshka** [comment]
Thanks for the heads up. I'll change this to use the floor of the character boundary instead.

**Comment by joshka** [comment]
Can you please take a look at https://github.com/joshka/tui-prompts/issues/56 and check that it solves your issue?

**Comment by frederictobiasc** [comment]
It does, thanks!

**Comment by joshka** [comment]
Released in https://github.com/joshka/tui-prompts/releases/tag/v0.3.15
